#!/usr/bin/perl

use ycp;
use diagnostics;

use strict;
use Getopt::Long;
use XML::Parser;
use POSIX qw(tmpnam);

y2milestone ("ag_xmltree started");

# read the agent arguments
#$_ = <STDIN>;
# no input at all - simply exit
#exit if ! defined $_;



while ( <STDIN> )
{
    my ($command, $path, $argument) = ycp::ParseCommand ($_);
    if ($command eq "Read" )
    {

	my   $file     =  $argument;
	my   $parser = new XML::Parser(Style => 'Tree');
	my   $tree = $parser->parsefile($file);


	ycp::Return ( $tree );

	
    }
    else
    {
	y2error ("Unknown instruction $command or argument: ", ref ($argument));
	ycp::Return ("false");
    }
    print "\n";
  
}

#EOF
